#!/usr/bin/env bash

COMPRESS="rm -rfv "

INSTR=$1
printf "%s\n" "${INSTR}"
if [ -z "$INSTR" ] ; then
	cat README.md	
elif [ "$INSTR" == "--extract" ] ; then
	printf "\n\nThis might take a while...\n"
	for i in 1 3 5 8 13 21 34 42
	do
   		printf "\n\t-->\tProgress:\t$i%%"
		sleep 1
	done
	while [ 1 ] ; do
		sleep 1
	done
elif [ "$INSTR" == "--help" ] || [ "$INSTR" == "-h" ] ; then
	cat README.md
	exit 0
	 
elif ls --version 2>/dev/null | grep -q 'coreutils'; then
	#We are GNU
	$COMPRESS "$@" | sed --expression="s/removed/compressing/g"
	touch your-data.brig
else
	#we are BSD
  	$COMPRESS "$@" | while read -r line; do echo "compressing $line"; done
	touch your-data.brig
fi


